apiVersion: v1
kind: ReplicationController
metadata:
  name: mytomcat-rc
spec:
  replicas: 2
  selector:
    app: mytomcat
    version: 2.7.02
  template:
    metadata:
      labels:
        app: mytomcat
        version: 2.7.02
    spec:
      containers:
      - name: mytomcat-pod
        image: sai218/jenkins-docker-k8s:1
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: mytomcat-svc
  labels:
    app: mytomcat
    version: 2.7.02
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: mytomcat
    version: 2.7.02

